version: 2
jobs:
  test-ruby:
    docker:
      # cf.: https://circleci.com/docs/2.0/docker-image-tags.json
      - image: circleci/ruby:2.6.0-stretch
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: cd ./ruby && bundle install
      - run:
          name: Run tests
          command: cd ./ruby && bundle exec rspec run.rb

  test-javascript:
    docker:
      - image: circleci/node:10.16.0-browsers
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: cd ./javascript && npm install
      - run:
          name: Run tests
          command: cd ./javascript && npm test

  test-python:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              cd ./python && python3 -m venv env
              . env/bin/activate
              pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
              cd ./python && . env/bin/activate
              pytest safe_spaces_test.py

  test-java:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers
    steps:
      - checkout
      - run:
          name: Run Tests
          command: cd ./java && ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-ruby
      - test-javascript
      - test-python
      - test-java

